feat: 支持事件拓展(EventExpansion) (#17)
[chore(command): 调整了command事件的存储位置](https://github.com/MemoryShadow/minecraftctl/commit/c5d45e794c4ba7da492aacab5dabd7051f14a326)
[chore: 放宽了匹配的规则, 令其大小写不敏感](https://github.com/MemoryShadow/minecraftctl/commit/70649d4e84f2cbf41148cff4490a68f705a21230)
[feat: 添加了.d目录, 允许令事件源触发脚本](https://github.com/MemoryShadow/minecraftctl/commit/0db44df25dd3d6494e3eaabbeef7078f8679c70f)
docs: 扩容了刹车机制的长度

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -204,8 +204,8 @@ jobs:
           sudo tar -xzf adoptopenjdk-8-openj9-jre.tar.gz -C /usr/lib/jvm/;
           rm adoptopenjdk-8-openj9-jre.tar.gz;
           # 部署pyCraft
-          git clone https://github.com/MemoryShadow/pyCraft.git ~/pyCraft;
-          pip install pynbt requests cryptography;
+          git clone --depth 1 -b master https://github.com/MemoryShadow/pyCraft.git ~/pyCraft;
+          pip install --user pynbt requests cryptography;
 
       - name: Install old-minecraftctl
         run: |
@@ -233,59 +233,19 @@ jobs:
           mkdir -p ~/D_MCServer;
           cd ~/D_MCServer;
           minecraftctl install -i vanilla -c -v 1.16.5;
+          if [ $? -ne 0 ]; then
+            echo "Install Minecraft Server failed.";
+            exit 1;
+          fi
           ls -labh; cat minecraftctl.conf;
 
       - name: Run Minecraft Server
         run: |
           # 生成一个随机ID, 这个ID也会成为在这个CI校验流程中的重要ID, 
           CheckID=`date +%s%N | md5sum | cut -c 1-10`;
+          echo -e "\n\nexport CheckID='${CheckID}'" | sudo tee -a /etc/minecraftctl/config;
 
-          #*新增start事件响应, 启动时拉起一个pyCraft实例
-          sudo tee -a "/opt/minecraftctl/event/INFO/start" >> /dev/null <<EOF;
-
-          echo "拉起一个pyCraft实例" >> /tmp/E_CICheck.log;
-          # 拉起一个pyCraft实例
-          ls -lab ./ >> /tmp/E_CICheck.log;
-          echo "======" >> /tmp/E_CICheck.log;
-          ls -lab ../ >> /tmp/E_CICheck.log;
-          echo "======" >> /tmp/E_CICheck.log;
-          ls -lab ~/ >> /tmp/E_CICheck.log;
-          cd ~/pyCraft;
-          echo "  创建会话" >> /tmp/E_CICheck.log;
-          screen -dmS "pyCraft";
-          echo "  设置权限" >> /tmp/E_CICheck.log;
-          chmod +x ./start.py;
-          # 上线
-          screen -x -S "pyCraft" -p 0 -X stuff "echo '  检查环境: ${CheckID} \${PWD}' >> /tmp/E_CICheck.log 2>&1\n";
-          screen -x -S "pyCraft" -p 0 -X stuff "./start.py -u ${CheckID} -s localhost -o >> /tmp/E_CICheck.log 2>&1\n";
-          EOF
-
-          #*新增login事件响应, 登陆时发送消息
-          sudo tee -a "/opt/minecraftctl/event/INFO/login" >>/dev/null <<EOF
-
-          echo "发送消息触发插件" >> /tmp/E_CICheck.log;
-          # 发送消息触发插件
-          screen -x -S "pyCraft" -p 0 -X stuff "\!\!ci ${CheckID}\n";
-          EOF
-
-          #*新增logout事件响应, 退出登陆时关闭服务端
-          sudo tee -a "/opt/minecraftctl/event/INFO/logout" >>/dev/null <<EOF
-
-          echo "玩家退出时自动关闭服务端" >> /tmp/E_CICheck.log;
-          # 玩家退出时自动关闭服务端
-          minecraftctl stop;
-          EOF
-
-          #*创建CI模块, 输出日志并关闭服务器
-          sudo tee "/opt/minecraftctl/command/ci" >/dev/null <<EOF
-          #!/bin/bash
-          cd ~/D_MCServer;
-          echo "\${1#*\!\!ci }" > /tmp/CICheck.log;
-          echo "退出登陆" >> /tmp/E_CICheck.log;
-          # 退出登陆
-          screen -S "pyCraft" -X quit;
-          EOF
-          sudo chmod +x "/opt/minecraftctl/command/ci";
+          minecraftctl install -mE -i ci
 
           #*启动服务
           sudo sed -i 's/> \/dev\/stderr;/>> \/tmp\/E_CICheck.log;/' /opt/minecraftctl/module/listen.sh;
@@ -307,7 +267,7 @@ jobs:
               cat /tmp/E_CICheck.log;
               exit 1;
             fi
-          done;
+          done
           cat /tmp/CICheck.log | grep ${CheckID};
 
       - name: Uninstall minecraftctl
