chore: try to fix can't install

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -103,12 +103,20 @@ jobs:
 
       - name: Install old-minecraftctl
         run: |
-          wget -O ~/minecraftctl_1.0.1_i386.deb https://github.com/MemoryShadow/minecraftctl/releases/download/v1.0.1/minecraftctl_1.0.1_i386.deb
-          sudo dpkg -i ~/minecraftctl_1.0.1_i386.deb
-          sed -i 's/GamePath=".*"/GamePath="Test"/' /etc/minecraftctl/config
-          build/Universal.sh update
-          grep Test /etc/minecraftctl/config
+          sudo build/Universal.sh install
           minecraftctl help
 
+      - name: Update minecraftctl
+        run: |
+          sudo sed -i 's/GamePath=".*"/GamePath="Test"/' /etc/minecraftctl/config
+          sudo build/Universal.sh update
+          grep Test /etc/minecraftctl/config
+          if [ $? -ne 0 ]; then
+            echo "Update config failed."
+            exit 1
+          fi
+          minecraftctl help
+          sudo build/Universal.sh uninstall
+
       - name: Install minecraftctl
-        run: build/Universal.sh install && minecraftctl help && build/Universal.sh install
+        run: sudo build/Universal.sh install && minecraftctl help && sudo build/Universal.sh uninstall
